/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#727780',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001c38',
        'on-error-container': '#93000a',
        'on-background': '#111c2d',
        'on-tertiary-fixed': '#002204',
        'on-tertiary-fixed-variant': '#005312',
        'on-surface-variant': '#42474f',
        'on-tertiary-container': '#84d67f',
        'surface-container-high': '#dee8ff',
        secondary: '#7a5900',
        'tertiary-container': '#035e17',
        'outline-variant': '#c2c6d1',
        'on-primary-fixed-variant': '#0d487e',
        'surface-bright': '#f9f9ff',
        tertiary: '#00440d',
        'secondary-fixed': '#ffdea3',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#a3f69c',
        'inverse-surface': '#263143',
        background: '#f9f9ff',
        'primary-container': '#1d5288',
        'on-primary-container': '#9cc6ff',
        surface: '#f9f9ff',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdbf31',
        'secondary-fixed-dim': '#fabd2e',
        'on-secondary-container': '#6e4f00',
        'primary-fixed-dim': '#a2c9ff',
        'on-secondary-fixed': '#261900',
        'on-surface': '#111c2d',
        'primary-fixed': '#d3e4ff',
        primary: '#003b6b',
        'inverse-primary': '#a2c9ff',
        'error-container': '#ffdad6',
        'surface-container': '#e7eeff',
        'on-secondary-fixed-variant': '#5d4200',
        'surface-variant': '#d8e3fb',
        'inverse-on-surface': '#ecf1ff',
        'surface-tint': '#2f6097',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#88d982',
        'surface-container-low': '#f0f3ff',
        'surface-container-highest': '#d8e3fb',
        'surface-dim': '#cfdaf2',
        'surface-container-lowest': '#ffffff',
        canvas: '#F8FAFC',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'button-text': ['Hanken Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'button-text': ['16px', { lineHeight: '24px', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'container-max-width': '1200px',
      },
      boxShadow: {
        active: '0 4px 12px rgba(29, 82, 136, 0.08)',
        lift: '0 4px 12px rgba(29, 82, 136, 0.12)',
      },
    },
  },
  plugins: [],
}
